DROP TABLE IF EXISTS CONGREGATION;

create table CONGREGATION (
ID INT NOT NULL PRIMARY key,
INSIDE_ID BIGINT NOT NULL,
NAME VARCHAR(64) not null,
HOME_NUM VARCHAR(16),
CELL_NUM VARCHAR(16),
EMAIL VARCHAR(128),
TEAM CHAR(8),
UPDATED_TS DATETIME ON UPDATE CURRENT_TIMESTAMP,
CREATED_TS DATETIME DEFAULT NOW()
);


ALTER TABLE CONGREGATION AUTO_INCREMENT = 1001;


INSERT CONGREGATION (ID, INSIDE_ID, NAME, HOME_NUM, CELL_NUM, EMAIL, TEAM ) 
VALUES(1001, 300983, "黃健豪", "4164984983", "4168035832", "woodspring.ontariospring@gmail.com", "協力二")